export const DEFAULT_CHAR_DHAM_PACKAGES = [
  {
    name: 'Char Dham Standard Package',
    category: 'standard',
    price: 35000,
    duration: '10 Days',
    seatsAvailable: 20,
    shortDescription: 'Budget-friendly Char Dham pilgrimage with comfortable stays.',
    fullDescription:
      'A value package covering Yamunotri, Gangotri, Kedarnath and Badrinath with planned transfers, meals and guided support.',
    highlights: ['Comfortable stays', 'Darshan assistance', 'All transfers'],
    included: ['Hotel stay', 'Meals as per plan', 'All transfers', 'Tour assistance'],
    excluded: ['Personal expenses', 'Helicopter (if any)', 'Porter/Pony charges'],
    specialFeatures: ['Best value'],
    itinerary: [
      { day: 1, title: 'Haridwar Arrival', description: '' },
      { day: 2, title: 'Yamunotri Darshan', description: '' },
      { day: 3, title: 'Gangotri Darshan', description: '' },
      { day: 4, title: 'Kedarnath Trek', description: '' },
      { day: 5, title: 'Badrinath Darshan', description: '' },
    ],
    isRecommended: true,
  },
  {
    name: 'Char Dham Premium Package',
    category: 'premium',
    price: 65000,
    duration: '10 Days',
    seatsAvailable: 10,
    shortDescription: 'Premium stays + better meals + smoother travel experience.',
    fullDescription:
      'Premium Char Dham pilgrimage with better hotels, priority planning and enhanced comfort across the yatra route.',
    highlights: ['Premium hotels', 'Better meal plan', 'Priority planning'],
    included: ['Premium hotel stay', 'Meals as per plan', 'All transfers', 'Tour manager'],
    excluded: ['Personal expenses', 'VIP Darshan fees (if applicable)'],
    specialFeatures: ['Comfort upgrade'],
    itinerary: [
      { day: 1, title: 'Haridwar Arrival', description: '' },
      { day: 2, title: 'Yamunotri Darshan', description: '' },
      { day: 3, title: 'Gangotri Darshan', description: '' },
      { day: 4, title: 'Kedarnath Trek / Assistance', description: '' },
      { day: 5, title: 'Badrinath Darshan', description: '' },
    ],
    isRecommended: true,
  },
  {
    name: 'Char Dham Luxury Package',
    category: 'luxury',
    price: 150000,
    duration: '10 Days',
    seatsAvailable: 5,
    shortDescription: 'Luxury hotels + VIP Darshan + helicopter ride option.',
    fullDescription:
      'Luxury Char Dham experience with top stays, VIP planning and exclusive features including helicopter ride options where available.',
    highlights: ['Luxury hotels', 'VIP Darshan', 'Helicopter ride option'],
    included: ['Luxury hotel stay', 'Meals', 'All transfers', 'Dedicated support'],
    excluded: ['Personal expenses', 'Extra helicopter charges (if any)'],
    specialFeatures: ['VIP Darshan', 'Helicopter Ride', 'Luxury Hotels'],
    itinerary: [
      { day: 1, title: 'Haridwar Arrival', description: '' },
      { day: 2, title: 'Yamunotri Darshan', description: '' },
      { day: 3, title: 'Gangotri Darshan', description: '' },
      { day: 4, title: 'Kedarnath Darshan', description: '' },
      { day: 5, title: 'Badrinath Darshan', description: '' },
    ],
    isRecommended: true,
  },
];

